// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PuntoVenta.Infrastructure.Persistence;

#nullable disable

namespace PuntoVenta.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("CustomerId");

                    b.HasIndex("DocumentNumber")
                        .HasDatabaseName("inx_documento");

                    b.HasIndex("LastName")
                        .HasDatabaseName("inx_apellido");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Av. Cevallos y Espejo",
                            City = "Ambato",
                            DocumentNumber = "1850123456",
                            Email = "juan.perez@gmail.com",
                            FirstName = "Juan",
                            LastName = "Pérez",
                            Phone = "0999999991"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Av. de los Shyris",
                            City = "Quito",
                            DocumentNumber = "1720123456",
                            Email = "maria.lopez@gmail.com",
                            FirstName = "María",
                            LastName = "López",
                            Phone = "0999999992"
                        });
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMBER(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ProductId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Teclado 1",
                            Price = 1.50m,
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Proyecto Epson",
                            Price = 0.80m,
                            Stock = 100
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Laptop HP ",
                            Price = 1.20m,
                            Stock = 30
                        });
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<byte>("PaymentType")
                        .HasColumnType("NUMBER(3)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<byte>("Status")
                        .HasColumnType("NUMBER(3)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.SaleDetail", b =>
                {
                    b.Property<int>("SaleDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleDetailId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SaleId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SaleDetailId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleDetails", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Sale", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.SaleDetail", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PuntoVenta.Domain.Entities.Sale", null)
                        .WithMany("Details")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
